# Twitter Create Gcal Event Login App Credentials #
TWITTER_CREATE_GCAL_EVENT_LOGIN_APP_API_KEY: ""
TWITTER_CREATE_GCAL_EVENT_LOGIN_APP_API_KEY_SECRET: ""

# Twitter Create Gcal Event Bot Credentials #
TWITTER_CREATE_GCAL_EVENT_BOT_API_KEY: ""
TWITTER_CREATE_GCAL_EVENT_BOT_API_KEY_SECRET: ""
