# Twitter Create Gcal Event Login App Credentials #
TWITTER_LOGIN_APP_API_KEY: ""
TWITTER_LOGIN_APP_API_KEY_SECRET: ""
TWITTER_LOGIN_APP_CALLBACK_URL: ""

# Twitter Create Gcal Event Bot Credentials #
TWITTER_CREATE_GCAL_EVENT_BOT_API_KEY: ""
TWITTER_CREATE_GCAL_EVENT_BOT_API_KEY_SECRET: ""

TOKEN_SECRET_SIGNING_KEY: ""

# Database
DB_HOST: "localhost"
DB_USER: "postgres"
DB_NAME: "postgres"
DB_PASSWORD: "password"
DB_PORT: "5432"

# Server
SERVER_PORT: "7000"

# Google API
GOOGLE_APP_CLIENT_SECRET: "" # paste the client secret json here