apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: aws-auth 
  namespace: kube-system 
data: 
  mapUsers: | 
    - userarn: arn:aws:iam::796007131872:user/twitter-space-gcal-event-github-ci
      username: twitter-space-gcal-event-github-ci
      groups:
        - system:masters